# Generated by Django 2.0 on 2017-12-10 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycoffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='bean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycoffee.Bean'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='boast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycoffee.Roast'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
