# Generated by Django 2.0 on 2017-12-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycoffee', '0002_auto_20171210_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='boast',
            new_name='roast',
        ),
    ]
