# Generated by Django 2.0 on 2017-12-10 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycoffee', '0003_auto_20171210_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='bean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycoffee.Bean'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='roast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycoffee.Roast'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
